export const SWITCH_EMAIL_NOTIFICATIONS = 'SWITCH_EMAIL_NOTIFICATIONS';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';

export const ERROR = {
  NOT_FOUND: 404,
};
